import type { WorkLog } from "../types";
import { generateId } from "../utils/id";
import { toISODate } from "../utils/format";

function daysFromToday(offset: number): string {
  const d = new Date();
  d.setDate(d.getDate() + offset);
  return toISODate(d);
}

function nowISO(): string {
  return new Date().toISOString();
}

export const initialMockLogs: WorkLog[] = [
  {
    id: generateId(),
    date: daysFromToday(-2),
    clientName: "Sarah Nguyen",
    work: "Full Glam Makeup",
    eventType: "Bridal",
    qty: 1,
    price: 350,
    startTime: "08:00",
    endTime: "11:00",
    amount: 350,
    paymentStatus: "PAID",
    status: "WORKED",
    own: true,
    referrerName: "",
    notes: "Bridal trial went great, used long-wear foundation.",
    createdAt: nowISO(),
    updatedAt: nowISO(),
  },
  {
    id: generateId(),
    date: daysFromToday(-2),
    clientName: "Priya Patel",
    work: "Bridesmaid Makeup",
    eventType: "Bridal Party",
    qty: 1,
    price: 120,
    startTime: "11:30",
    endTime: "12:30",
    amount: 120,
    paymentStatus: "PAID",
    status: "WORKED",
    own: false,
    referrerName: "Sarah's planner",
    notes: "",
    createdAt: nowISO(),
    updatedAt: nowISO(),
  },
  {
    id: generateId(),
    date: daysFromToday(-1),
    clientName: "Emma Clarke",
    work: "Editorial Look",
    eventType: "Photoshoot",
    qty: 1,
    price: 200,
    startTime: "14:00",
    endTime: "17:00",
    amount: 200,
    paymentStatus: "PENDING",
    status: "WORKED",
    own: true,
    referrerName: "",
    notes: "Invoice sent, awaiting payment.",
    createdAt: nowISO(),
    updatedAt: nowISO(),
  },
  {
    id: generateId(),
    date: daysFromToday(0),
    clientName: "Jasmine Lee",
    work: "Soft Glam",
    eventType: "Birthday Party",
    qty: 1,
    price: 90,
    startTime: "17:00",
    endTime: "18:30",
    amount: 90,
    paymentStatus: "PENDING",
    status: "WORKED",
    own: true,
    referrerName: "",
    notes: "",
    createdAt: nowISO(),
    updatedAt: nowISO(),
  },
  {
    id: generateId(),
    date: daysFromToday(5),
    clientName: "Olivia Martins",
    work: "Bridal Makeup",
    eventType: "Bridal",
    qty: 1,
    price: 400,
    startTime: "07:00",
    endTime: "10:00",
    amount: 400,
    paymentStatus: "PENDING",
    status: "RESERVED",
    own: true,
    referrerName: "",
    notes: "Deposit received, final payment on the day.",
    createdAt: nowISO(),
    updatedAt: nowISO(),
  },
  {
    id: generateId(),
    date: daysFromToday(12),
    clientName: "Grace Kim",
    work: "Party Makeup",
    eventType: "Party",
    qty: 1,
    price: 100,
    startTime: "16:00",
    endTime: "17:00",
    amount: 100,
    paymentStatus: "PENDING",
    status: "RESERVED",
    own: false,
    referrerName: "Meera",
    notes: "",
    createdAt: nowISO(),
    updatedAt: nowISO(),
  },
  {
    id: generateId(),
    date: daysFromToday(-20),
    clientName: "Isabella Rossi",
    work: "Full Glam Makeup",
    eventType: "Gala",
    qty: 1,
    price: 180,
    startTime: "18:00",
    endTime: "19:30",
    amount: 180,
    paymentStatus: "PAID",
    status: "WORKED",
    own: true,
    referrerName: "",
    notes: "",
    createdAt: nowISO(),
    updatedAt: nowISO(),
  },
];
